name: Basic Github Actions YAML

on: 
    push: 

jobs: 
    testing: 
        name: Testing files
        runs-on: ubuntu-latest
        steps:
            - name: reading repo files using actions
              uses: actions/checkout@v4
            - name: listing files
              run:  | 
                        echo "Welcome to Github Actions"
                        ls -la
                        cat index.html 
            # - name: ASCII Artwork
            #   run: cowsay  -f  dragon   "Run for cover,   Dragon is there"
